//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSBroadcast.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broadcast
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Messsage { get; set; }
        public System.DateTime BroadcastDateTime { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
